AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Managed by AWS SAM
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs22.x

Resources:
  GithubFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: github/
      Description: Managed by AWS SAM
      Events:
        Github:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#httpapi
          Properties:
            Path: /github
            Method: post
      Environment:
        Variables:
          MY_ACCESS_TOKEN: !Ref GithubMyAccessToken
          GITHUB_TITLE_IGNORE_REGEXP: !Ref GithubTitleIgnoreRegexp
          GITHUB_TITLE_PUSHOVER_REGEXP: !Ref GithubTitlePushoverRegexp
          PUSHOVER_APP_TOKEN: !Ref PushoverAppToken
          PUSHOVER_USER_KEY: !Ref PushoverUserKey
          MASTODON_URL: !Ref MastodonUrl
          MASTODON_ACCESS_TOKEN: !Ref MastodonAccessToken
      Timeout: 180 # seconds (default: 3)
  HatebuFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hatebu/
      Description: Managed by AWS SAM
      Events:
        Hatebu:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#httpapi
          Properties:
            Path: /hatebu
            Method: post
      Environment:
        Variables:
          MY_ACCESS_TOKEN: !Ref HatebuMyAccessToken
          PUSHOVER_APP_TOKEN: !Ref PushoverAppToken
          PUSHOVER_USER_KEY: !Ref PushoverUserKey
          MASTODON_URL: !Ref MastodonUrl
          MASTODON_ACCESS_TOKEN: !Ref MastodonAccessToken
      Timeout: 180 # seconds (default: 3)
  GithubFunctionAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:OrdinaryLambdaError"
      AlarmDescription: Any errors occurred in masutaka-feed-GithubFunction
      AlarmName: masutaka-feed-GithubFunction-errors
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref GithubFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 900 # 15 minutes
      Statistic: Sum
      Threshold: 0
      TreatMissingData: ignore
  HatebuFunctionAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:OrdinaryLambdaError"
      AlarmDescription: Any errors occurred in masutaka-feed-HatebuFunction
      AlarmName: masutaka-feed-HatebuFunction-errors
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref HatebuFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 900 # 15 minutes
      Statistic: Sum
      Threshold: 0
      TreatMissingData: ignore

Parameters:
  GithubMyAccessToken:
    Type: String
  GithubTitleIgnoreRegexp:
    Type: String
  GithubTitlePushoverRegexp:
    Type: String
  HatebuMyAccessToken:
    Type: String
  PushoverAppToken:
    Type: String
  PushoverUserKey:
    Type: String
  MastodonUrl:
    Type: String
  MastodonAccessToken:
    Type: String

Outputs:
  # ServerlessHttpApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GithubApi:
    Description: "API Gateway endpoint URL for Github function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/github/"
  GithubFunction:
    Description: "Github Lambda Function ARN"
    Value: !GetAtt GithubFunction.Arn
  GithubFunctionIamRole:
    Description: "Implicit IAM Role created for Github function"
    Value: !GetAtt GithubFunctionRole.Arn
  HatebuApi:
    Description: "API Gateway endpoint URL for Hatebu function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/hatebu/"
  HatebuFunction:
    Description: "Hatebu Lambda Function ARN"
    Value: !GetAtt HatebuFunction.Arn
  HatebuFunctionIamRole:
    Description: "Implicit IAM Role created for Hatebu function"
    Value: !GetAtt HatebuFunctionRole.Arn
