name: Dependency Review

on: [pull_request]

jobs:
  dependency_review:
    uses: masutaka/actions/.github/workflows/dependency_review.yml@main
    permissions:
      contents: read
      pull-requests: write
