name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  actionlint:
    uses: masutaka/actions/.github/workflows/actionlint.yml@main
    permissions:
      contents: read
  codeql:
    uses: masutaka/actions/.github/workflows/codeql.yml@main
    permissions:
      actions: read
      contents: read
      pull-requests: read
      security-events: write
  lint:
    runs-on: ubuntu-slim
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".tool-versions"
          cache: npm
          cache-dependency-path: |
            github/notifier/package-lock.json
            github/subscriber/package-lock.json
            hatebu/notifier/package-lock.json
            hatebu/subscriber/package-lock.json
      - run: make setup lint
  pushover:
    name: pushover if failure
    if: github.ref_name == github.event.repository.default_branch && failure()
    needs: [actionlint, codeql, lint]
    uses: masutaka/actions/.github/workflows/pushover.yml@main
    permissions: {}
    secrets:
      PUSHOVER_API_KEY: ${{ secrets.PUSHOVER_API_KEY }}
      PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
